#!/bin/bash


# Install JQ JSON parser
yum install -y jq aws-cli vim-enhanced
# Get the current region from the instance metadata
region=$(curl -s http://169.254.169.254/latest/dynamic/instance-identity/document | jq -r .region)
# Install the SSM agent RPM
yum install -y https://amazon-ssm-$region.s3.amazonaws.com/latest/linux_amd64/amazon-ssm-agent.rpm


# Install awslogs agent
yum install -y awslogs

sed -e s/us-east-1/${region}/ -i /etc/awslogs/awscli.conf

service awslogs start
chkconfig awslogs on
